<a href="https://colab.research.google.com/github/JonathanUtec/etl-data-pipeline2517202022/blob/main/EV2_Clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 37.1 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [ ]:
from sqlalchemy import create_engine
import pandas as pd
url = "postgresql://etl_seguros_pt9w_user:sPEaRFPJytaIDuQtIeQhkKp9jDmPpWCp@dpg-d6qu7bkr85hc73f4967g-a.oregon-postgres.render.com/etl_seguros_pt9w"
engine = create_engine(url)
test = pd.read_sql("SELECT 1", engine)
print(test)

   ?column?
0         1

Limpieza de datos | Clientes

In [ ]:
import pandas as pd

In [26]:
url = "https://raw.githubusercontent.com/JonathanUtec/etl-data-pipeline2517202022/refs/heads/main/data/raw/C_clientes%20(1).csv"

In [28]:
df = pd.read_csv(url)

In [29]:
df.head()

  id_cliente            cliente                  correo        ciudad
0      CL100   Comercial Díaz 0  cliente065@empresa.com     Santa Ana
1      CL101      Grupo Ideal 1    cliente131@correo.sv  San Salvador
2      CL102      Grupo Ideal 2  cliente211@empresa.com    San Miguel
3      CL103  Almacenes Prado 3    cliente329@gmail.com     Santa Ana
4      CL104    Soluciones CR 4    cliente441@gmail.com   La Libertad

In [33]:
#Limpieza de datos
clientes = df.copy()

clientes.columns = clientes.columns.str.strip().str.lower()

for col in clientes.select_dtypes("object"):
    clientes[col] = clientes[col].str.strip().str.lower()

clientes = clientes.replace(r'^\s*$', pd.NA, regex=True)

clientes = clientes.drop_duplicates()

clientes.head()

  id_cliente            cliente                  correo        ciudad
0      cl100   comercial díaz 0  cliente065@empresa.com     santa ana
1      cl101      grupo ideal 1    cliente131@correo.sv  san salvador
2      cl102      grupo ideal 2  cliente211@empresa.com    san miguel
3      cl103  almacenes prado 3    cliente329@gmail.com     santa ana
4      cl104    soluciones cr 4    cliente441@gmail.com   la libertad

In [34]:
#Separacion de datos
validos = clientes[
    clientes['cliente'].notna() &
    clientes['correo'].notna() &
    clientes['ciudad'].notna()
].copy()

rechazados = clientes[
    clientes['cliente'].isna() |
    clientes['correo'].isna() |
    clientes['ciudad'].isna()
].copy()

In [37]:
#Motivo de rechazo
def motivo(row):

    motivos = []

    if pd.isna(row['cliente']):
        motivos.append("cliente_vacio")

    if pd.isna(row['correo']):
        motivos.append("correo_vacio")

    if pd.isna(row['ciudad']):
        motivos.append("ciudad_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [38]:
#Exportar archivos
validos.to_csv("clientes_validos.csv", index=False)
rechazados.to_csv("clientes_rechazados.csv", index=False)

In [39]:
#Conectar con PostgreSQL
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

engine = create_engine(
"postgresql://etl_seguros_pt9w_user:sPEaRFPJytaIDuQtIeQhkKp9jDmPpWCp@dpg-d6qu7bkr85hc73f4967g-a.oregon-postgres.render.com/etl_seguros_pt9w"
)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [42]:
#Cargar datos en PostgreSQL
validos.to_sql(
    "clientes_curated",
    engine,
    if_exists="replace",
    index=False
    )

rechazados.to_sql(
    "clientes_rejects",
    engine,
    if_exists="replace",
    index=False
    )

3

In [46]:
#Validar la carga
pd.read_sql(
"SELECT * FROM clientes_curated LIMIT 10",
engine
)

  id_cliente                cliente                  correo        ciudad
0      cl100       comercial díaz 0  cliente065@empresa.com     santa ana
1      cl101          grupo ideal 1    cliente131@correo.sv  san salvador
2      cl102          grupo ideal 2  cliente211@empresa.com    san miguel
3      cl103      almacenes prado 3    cliente329@gmail.com     santa ana
4      cl104        soluciones cr 4    cliente441@gmail.com   la libertad
5      cl105  distribuciones luna 5  cliente592@empresa.com     santa ana
6      cl106          grupo ideal 6  cliente619@outlook.com  san salvador
7      cl107      almacenes prado 7   cliente75@empresa.com  san salvador
8      cl108         empresa nova 8  cliente861@outlook.com     santa ana
9      cl109  distribuciones luna 9    cliente998@correo.sv   la libertad