<a href="https://colab.research.google.com/github/JonathanUtec/etl-data-pipeline2517202022/blob/main/EV2_Ventas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install sqlalchemy psycopg2-binary
from sqlalchemy import create_engine
import pandas as pd
url = "postgresql://etl_seguros_pt9w_user:sPEaRFPJytaIDuQtIeQhkKp9jDmPpWCp@dpg-d6qu7bkr85hc73f4967g-a.oregon-postgres.render.com/etl_seguros_pt9w"
engine = create_engine(url)
test = pd.read_sql("SELECT 1", engine)
print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 23.6 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

Limpieza de datos | Ventas

In [2]:
import pandas as pd
url = "https://raw.githubusercontent.com/JonathanUtec/etl-data-pipeline2517202022/refs/heads/main/data/raw/C_ventas%20(1).csv"
df = pd.read_csv(url)
df.head()

  id_venta id_cliente       fecha    total
0    V9000      CL154  2024-10-25  4641.86
1    V9001      CL243  2024-06-29  1138.59
2    V9002      CL111  2024-01-25  1873.39
3    V9003      CL244  2024-01-26      NaN
4    V9004      CL243  2024-05-24  2208.24

In [7]:
#Limpieza de datos
Ventas = df.copy()

for col in Ventas.select_dtypes("object"):
    Ventas[col] = Ventas[col].str.strip().str.lower()


Ventas['fecha'] = pd.to_datetime(Ventas['fecha'], errors='coerce')
Ventas['fecha'] = Ventas['fecha'].dt.strftime('%Y/%m/%d')

Ventas['total'] = Ventas['total'].astype(str).str.replace('$', '', regex=False).str.replace('USD', '', regex=False).str.strip()
Ventas['total'] = pd.to_numeric(Ventas['total'], errors='coerce')

Ventas = Ventas.drop_duplicates()

Ventas.head(17)

   id_venta id_cliente       fecha    total
0     v9000      cl154  2024/10/25  4641.86
1     v9001      cl243  2024/06/29  1138.59
2     v9002      cl111  2024/01/25  1873.39
3     v9003      cl244  2024/01/26      NaN
4     v9004      cl243  2024/05/24  2208.24
5     v9005      cl239  2024/09/10  3072.44
6     v9006      cl235  2024/11/01  4716.52
7     v9007      cl102  2025/03/07  1218.65
8     v9008      cl243  2024/11/30   625.08
9     v9009      cl129  2024/12/10  1003.40
10    v9010      cl122  2024/08/28  4436.89
11    v9011      cl191  2024/05/26  3236.14
12    v9012      cl214         NaN  1443.82
13    v9013      cl203         NaN  4083.42
14    v9014      cl217  2025/03/09  4309.62
15    v9015      cl104  2024/02/25  4235.64
16    v9016      cl203  2024/08/08  4596.25

In [10]:
#Separación de datos
ventasValidos = Ventas[
    Ventas['id_venta'].notna() &
    Ventas['id_cliente'].notna() &
    Ventas['fecha'].notna() &
    Ventas['total'].notna()
].copy()

ventasRechazados = Ventas[
    Ventas['id_venta'].isna() |
    Ventas['id_cliente'].isna() |
    Ventas['fecha'].isna() |
    Ventas['total'].isna()
].copy()

In [11]:
#Motivo de rechazo
def motivo(row):

    motivos = []

    if pd.isna(row['id_venta']):
        motivos.append("idVenta_vacio")

    if pd.isna(row['id_cliente']):
        motivos.append("idCliente_vacio")

    if pd.isna(row['fecha']):
        motivos.append("fecha_vacio")

    if pd.isna(row['total']):
        motivos.append("total_vacio")

    return ",".join(motivos)

ventasRechazados["motivo_rechazo"] = ventasRechazados.apply(motivo, axis=1)

In [17]:
#Exportar archivos
ventasValidos.to_csv("ventas_validos.csv", index=False)
ventasRechazados.to_csv("ventas_rechazados.csv", index=False)

In [13]:
#Conectar con PostgreSQL
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

engine = create_engine(
"postgresql://etl_seguros_pt9w_user:sPEaRFPJytaIDuQtIeQhkKp9jDmPpWCp@dpg-d6qu7bkr85hc73f4967g-a.oregon-postgres.render.com/etl_seguros_pt9w"
)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [14]:
#Cargar datos en PostgreSQL
ventasValidos.to_sql(
    "ventas_curated",
    engine,
    if_exists="replace",
    index=False
    )

ventasRechazados.to_sql(
    "ventas_rejects",
    engine,
    if_exists="replace",
    index=False
    )

35

In [16]:
#Validar la carga
pd.read_sql(
"SELECT * FROM ventas_curated LIMIT 10",
engine
)

  id_venta id_cliente       fecha    total
0    v9000      cl154  2024/10/25  4641.86
1    v9001      cl243  2024/06/29  1138.59
2    v9002      cl111  2024/01/25  1873.39
3    v9004      cl243  2024/05/24  2208.24
4    v9005      cl239  2024/09/10  3072.44
5    v9006      cl235  2024/11/01  4716.52
6    v9007      cl102  2025/03/07  1218.65
7    v9008      cl243  2024/11/30   625.08
8    v9009      cl129  2024/12/10  1003.40
9    v9010      cl122  2024/08/28  4436.89