<a href="https://colab.research.google.com/github/JonathanUtec/etl-data-pipeline2517202022/blob/main/EV2_Pagos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install sqlalchemy psycopg2-binary
from sqlalchemy import create_engine
import pandas as pd
url = "postgresql://etl_seguros_pt9w_user:sPEaRFPJytaIDuQtIeQhkKp9jDmPpWCp@dpg-d6qu7bkr85hc73f4967g-a.oregon-postgres.render.com/etl_seguros_pt9w"
engine = create_engine(url)
test = pd.read_sql("SELECT 1", engine)
print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 26.8 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

Limpieza de datos | Pagos

In [5]:
from pandas.io.api import read_csv
import pandas as pd
url = "https://raw.githubusercontent.com/JonathanUtec/etl-data-pipeline2517202022/refs/heads/main/data/raw/C_pagos%20(1).csv"
df = pd.read_csv(url)
df.head()

  id_pago id_venta         metodo monto_pagado
0  PG8000    V9057  Transferencia      4452.68
1  PG8001    V9027  Transferencia      1742.47
2  PG8002    V9025        Tarjeta       789.21
3  PG8003    V9112  Transferencia       146.73
4  PG8004    V9190       Efectivo       3236.2

In [10]:
#Limpieza de datos
Pagos = df.copy()

for col in Pagos.select_dtypes("object"):
    Pagos[col] = Pagos[col].str.strip().str.lower()

Pagos['monto_pagado'] = Pagos['monto_pagado'].astype(str).str.replace('$', '', regex=False).str.replace('USD', '', regex=False).str.strip()
Pagos['monto_pagado'] = pd.to_numeric(df['monto_pagado'], errors='coerce')

Pagos = Pagos.replace(r'^\s*$', pd.NA, regex=True)

Pagos = Pagos.drop_duplicates()

Pagos.head()

  id_pago id_venta         metodo  monto_pagado
0  pg8000    v9057  transferencia       4452.68
1  pg8001    v9027  transferencia       1742.47
2  pg8002    v9025        tarjeta        789.21
3  pg8003    v9112  transferencia        146.73
4  pg8004    v9190       efectivo       3236.20

In [28]:
#Separación de datos
pagosValidos = Pagos[
    Pagos['id_pago'].notna() &
    Pagos['id_venta'].notna() &
    Pagos['metodo'].notna() &
    Pagos['monto_pagado'].notna()
].copy()

pagosRechazados = Pagos[
    Pagos['id_pago'].isna() |
    Pagos['id_venta'].isna() |
    Pagos['metodo'].isna() |
    Pagos['monto_pagado'].isna()
].copy()

In [29]:
#Motivo de rechazo
def motivo(row):

    motivos = []

    if pd.isna(row['id_pago']):
        motivos.append("idPago_vacio")

    if pd.isna(row['id_venta']):
        motivos.append("idVenta_vacio")

    if pd.isna(row['metodo']):
        motivos.append("metodo_vacio")

    if pd.isna(row['monto_pagado']):
        motivos.append("montoPagado_vacio")

    return ",".join(motivos)

pagosRechazados["motivo_rechazo"] = pagosRechazados.apply(motivo, axis=1)

In [30]:
#Exportar archivos
pagosValidos.to_csv("pagos_validos.csv", index=False)
pagosRechazados.to_csv("pagos_rechazados.csv", index=False)

In [24]:
#Conectar con PostgreSQL
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

engine = create_engine(
"postgresql://etl_seguros_pt9w_user:sPEaRFPJytaIDuQtIeQhkKp9jDmPpWCp@dpg-d6qu7bkr85hc73f4967g-a.oregon-postgres.render.com/etl_seguros_pt9w"
)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [31]:
#Cargar datos en PostgreSQL
pagosValidos.to_sql(
    "pagos_curated",
    engine,
    if_exists="replace",
    index=False
    )

pagosRechazados.to_sql(
    "pagos_rejects",
    engine,
    if_exists="replace",
    index=False
    )

25

In [32]:
#Validar la carga
pd.read_sql(
"SELECT * FROM pagos_rejects LIMIT 10",
engine
)

  id_pago id_venta         metodo  monto_pagado     motivo_rechazo
0  pg8029     None         cheque       2303.44      idVenta_vacio
1  pg8038     None       efectivo       4920.39      idVenta_vacio
2  pg8039    v9175         cheque           NaN  montoPagado_vacio
3  pg8042     None        tarjeta       1939.85      idVenta_vacio
4  pg8052     None     pago móvil       1311.49      idVenta_vacio
5  pg8055    v9113       efectivo           NaN  montoPagado_vacio
6  pg8095    v9026  transferencia           NaN  montoPagado_vacio
7  pg8106    v9132         cheque           NaN  montoPagado_vacio
8  pg8116    v9210        tarjeta           NaN  montoPagado_vacio
9  pg8120    v9138        tarjeta           NaN  montoPagado_vacio